### PR TITLE
Adding k8s 1.22 flavor

### PR DESCRIPTION
**Pull request by vlella**

### CODE REVIEW

**Comment by snaiksat** [comment]
Thanks @vlella , we also need to keep moving the default flavor in the UTs to use the latest (we might have not done it on previous occasions).

**Comment by vlella** [comment]
I guess updating https://github.com/noironetworks/acc-provision/blob/master/provision/acc_provision/test_main.py#L737 this to 1.22, I am hoping thats what you meant above Sumit.

**Comment by snaiksat** [comment]
Yes @vlella .

**Comment by snaiksat** [comment]
Please update the UTs.

**Comment by snaiksat** [comment]
@vlella we need to do end to end validation. Please coordinate with @anmol372 (there is a separate issue for that).

**Review by snaiksat — APPROVED** [review]

**Pull request merged**
