### PR TITLE
Generalize APIC resources name according to the container ecosystem

### PR DESCRIPTION
**Pull request by apoorva11029**
Added option to add "app_profile" as part of the input file to acc-provision, defaults according to the flavor name: "openshift", "dockerucp", and kubernetes for the rest.

More info: noironetworks/support#845

### CODE REVIEW

**Comment by puppet-py** [comment]
Since we want to breakout from our generalized app_profile name(currently kubernetes used for both K8s and Openshift deployment), we should set the default string on checking with the flavor. In this current PR, if Openshift user does not explicitly mention the app_profile we will land up creating "kubernetes" which defies our intent.
So I would suggest, create the default string(app_profile) based on the flavor passed

**Comment by apoorva11029** [comment]
@puppet-py added the change

**Comment by puppet-py** [comment]
We have one more flavor "cloudfoundry" :-), the app_profile corresponding to it should "cloud-foundry". Sorry missed out in pointing this to you earlier in the email-thread

**Comment by apoorva11029** [comment]
@puppet-py we don't need to provide an option for setting the app_profile for cloudfoundry as it's handled separately in the code already

**Pull request closed without merging**
