### PR TITLE
Add flavor for openshift 4.5 on openstack

### PR DESCRIPTION
**Pull request by apoorva11029**
The setting are similar for the 4.4 flavor

### CODE REVIEW

**Comment by snaiksat** [comment]
No UT for 4.5 flavor? I know it will be a duplication of the 4.4 UT, but it will be good to add explicitly (if in the future a few things diverge).

**Comment by snaiksat** [comment]
We also need to do the same thing for the OpenShift on ESX flavor.

**Comment by apoorva11029** [comment]
> No UT for 4.5 flavor? I know it will be a duplication of the 4.4 UT, but it will be good to add explicitly (if in the future a few things diverge).

Added.

**Comment by apoorva11029** [comment]
> We also need to do the same thing for the OpenShift on ESX flavor.

There's a UT for that flavor in the code already :)

**Review by abhis2112 — APPROVED** [review]

**Pull request merged**
