### PR TITLE
Bumping release to 6.0.0.0

### PR DESCRIPTION
**Pull request by anmol372**

### CODE REVIEW

**Comment by snaiksat** [comment]
Thanks @anmol372 . We would have regenerate the test files though. :-(

**Comment by snaiksat** [comment]
@vlella please take note of this PR for feature, on the release branches (eg kwai, kmr2, etc) also we do something similar. We did one yesterday in fact on kmr2.

**Comment by snaiksat** [comment]
@anmol372 the tests are passing because 6.0 version is not the default. We would have to change in in the flavors.yaml (then the tests would fail and we would need to update the test data).

**Comment by anmol372** [comment]
> Thanks @anmol372 . We would have regenerate the test files though. :-(

I ran fix-tesdata but no new files generated, I think I need to update the tests to use the release as well. Will update soon.

**Comment by anmol372** [comment]
Build is failing as coveralls.io api is down. Monitoring it and will restart build once that's back up.

**Comment by anmol372** [comment]
coveralls service is back and CI is passing.

**Review by snaiksat — APPROVED** [review]

**Review by snaiksat — CHANGES_REQUESTED** [review]
nit (but important) - can you change the commit message to:
Bumping release to 6.0.0.0

**Review by snaiksat — APPROVED** [review]

**Pull request merged**
