### PR TITLE
Added changes to get NAD VLAN mapping info from csv file and prepare …

### PR DESCRIPTION
**Pull request by YogeshRajmane**
…NAD VLAN map CR

### CODE REVIEW

**Comment by snaiksat** [comment]
Thanks @YogeshRajmane . Can we add a UT which reads a CSV, populates the CR, and then validates it with the expected output?

**Comment by YogeshRajmane** [comment]
> Thanks @YogeshRajmane . Can we add a UT which reads a CSV, populates the CR, and then validates it with the expected output?

Sanjib prepared UT and I added that in same PR.

**Comment by shastrinator** [comment]
Can you please use the latest image and try it on the cluster once..

**Comment by shastrinator** [comment]
Changes look ok

**Comment by shastrinator** [comment]
I have updated the staticfabricattachment CR, so please update in the changeset as well. [https://raw.githubusercontent.com/noironetworks/aci-containers/master/pkg/hostagent/testdata/aci.fabricattachment_staticfabricnetworkattachments.yaml](url)

**Review by snaiksat — APPROVED** [review]

**Pull request merged**
