### PR TITLE
generate argo spec

### PR DESCRIPTION
**Pull request by psolarcz**
Generate argo spec by acc-provision, it requires:

``` bash
gitops:
  base64_encoded_argo_manifests:
```

in config.yaml

### CODE REVIEW

**Review by tanyatukade — APPROVED** [review]
LGTM

**Comment by tanyatukade** [comment]
I dont see the testdata files updated, Can we add this config in the test input file and generate the output test files?

**Comment by tanyatukade** [comment]
> Generate argo spec by acc-provision, it requires:
> 
> ```shell
> gitops:
>   base64_encoded_argo_manifests:
> ```
> 
> in config.yaml

what should be the value of "base64_encoded_argo_manifests" key in the above config?

**Comment by psolarcz** [comment]
> 

It should be empty. I had to add it because it was complaining that: `gitops` is a str and cannot add new key to it.

**Review by snaiksat — APPROVED** [review]

**Pull request merged**
